### ISSUE TITLE
nginx: [warn] and [emerg] | config failed

### ISSUE THREAD

**Issue by kenetik** [matomo-org/matomo-nginx#13]
``` shell
nginx: [warn] server name "$scheme://stats.example.com$request_uri" has suspicious symbols in /etc/nginx/sites-enabled/stats.example.com:15
nginx: [emerg] "expires" directive is duplicate in /etc/nginx/apps/piwik/proxy_piwik_cache.conf:30
nginx: configuration file /etc/nginx/nginx.conf test failed
```

*Note: I put stats.example back in for privacy reasons.

**Comment by hochitom** [comment]
same here. does anybody got it to work?

**Comment by approached** [comment]
expires is duplicated so you can disable in:
```
"expires" directive is duplicate in /etc/nginx/apps/piwik/proxy_piwik_cache.conf:30
```

to enable the proxycache for the piwik.php you can just uncomment follow line in **nginx.conf**:
```
    ## Proxy cache zone definition.
    ## Uncomment to enable.
    include proxy_cache_zone.conf;
```

**Comment by approached** [comment]
you must disable the proxy cache:
```
vi /etc/nginx/apps/piwik/piwik.conf

location = /index.php {
    fastcgi_pass phpcgi;
    ## FastCGI cache.
    ## cache ui for 5m (set the same interval of your crontab)
    include apps/piwik/fcgi_piwik_cache.conf;
    ## To use Apache for serving PHP uncomment the line bellow and
    ## comment out the above.
    #proxy_pass http://phpapache;
    ### Use the proxy cache if proxying to Apache.
    #include apps/piwik/proxy_piwik_cache.conf;   <---
}
```

**Comment by cptmashek** [comment]
When I disable the proxy cache, I then get:
```
nginx: [emerg] "fastcgi_cache" zone "fcgicache" is unknown in /etc/nginx/nginx.conf:41
nginx: configuration file /etc/nginx/nginx.conf test failed
```
However, line 41 is the ending bracket.

**Comment by PabloCastellano** [comment]
Just got it issue on Ubuntu 14.04 and nginx 1.4.6-1ubuntu.

Workaround:
- Disable the proxy cache as https://github.com/perusio/piwik-nginx/issues/13#issuecomment-74668315
- Add your domain to valid referers if you are missing css and images:

diff --git a/apps/piwik/piwik.conf b/apps/piwik/piwik.conf
index 71609c7..1cc3fd4 100644
--- a/apps/piwik/piwik.conf
+++ b/apps/piwik/piwik.conf
@@ -6,7 +6,7 @@ location / {
     ## Disallow any usage of piwik assets if referer is non valid.
     location ~* ^.+\.(?:css|gif|html?|jpe?g|js|png|swf)$ {
         ## Defining the valid referers.
-        valid_referers none blocked *.mysite.com othersite.com;
+        valid_referers none blocked *.mysite.com othersite.com your.piwik.domain.here.;
         if ($invalid_referer)  {
             return 444;
         }

cc @vacri

**Comment by snape84** [comment]
Even i know that this conversation is a couple of years old: I have same problem here and the workaround explained above does not work for me. I use nginx with php7.0-fpm, so i commented all the proxy configuration (longcache and cache), entered my domain into the valid referers and created a direcory /var/cache/fcgicache owned by www-data. 
 As ghost 
mensioned, i get same error: 
nginx: [emerg] "fastcgi_cache" zone "fcgicache" is unknown in /etc/nginx/nginx.conf:64
Any other ideas?
