### ISSUE TITLE
Configure script

### ISSUE THREAD

**Issue by rlaferla** [matomo-org/matomo-nginx#20]
Installing Piwik on nginx is simply a pain.  A configure script where the user types in a domain name would really help.  Especially one that knew what dependencies to install (Amazon EC2 needs PHP 5.5, nginx, mysql, etc...)

**Comment by anupamapanchal** [comment]
Agreed with @rlaferla . Its been more than 24 hours that I am trying to install it on Amazon EC2 but series of problems are coming. Documentation is not that helpful.
