### ISSUE TITLE
Best practice for combing two of your configs with SSL

### ISSUE THREAD

**Issue by luxpir** [matomo-org/matomo-nginx#24]
Obviously there's a lot of overlap between your various configs, so I've tried to take that into account. I've had a solid drupal + piwik config combination working previously, but after updating both Piwik and the Drupal site, enabling SSL with SPDY, the Piwik end 'dropped off' (I'm getting 404s at the moment, but also had bad gateway 502 errors with a few tweaks...).

I'm having trouble piecing the right config back together. I have a piwik.conf in sites-enabled, as per your example, which includes the apps/piwik/piwik.conf file also. The latter seems to have no effect on a TLS/SSL setup. I've done the following with the former (sites-enabled/piwik.conf):

```
server {
    listen 80;
    server_name piwik;
    return 301 https://www.domainname.com/piwik/$request_uri;
}

server {
    listen 443 ssl spdy;

    limit_conn arbeit 32;
    server_name piwik1;
    keepalive_timeout 75 75;

    ssl_certificate /etc/ssl/certs/acme.pem;
    ssl_certificate_key /etc/ssl/private/acme.key;

    ## Access and error log files.
    access_log /var/log/nginx/stats.domainname.com_access.log;
    error_log /var/log/nginx/stats.domainname.com_error.log;

    root /usr/share/nginx/www/piwik;
    index index.php;

    ## Include the piwik configuration.
    include apps/piwik/piwik.conf;
}
```

I'll admit having a weak grasp on server_names when used with sub-directories and, well, nginx in general at times.

In the apps/piwik/piwik.conf file I did try to adjust the location blocks to include /piwik before each location (ie. /piwik/favicon.ico etc.) but that didn't seem to do it either, esp. given that the root is given in the sites-enabled config.

Any idea where I'm going wrong, and what others have done to fix this?

Thanks in advance.

**Comment by perusio** [comment]
Hallo,

Note that TLS requires either a dedicated IP or a valid server name that
agrees with the Common Name in the certificate.

piwik1 is not a valid domain name.

**Comment by luxpir** [comment]
Thanks for that. Yep, changed that to a subdomain, returning a 301 to https://domainname.com/piwik/index.php, which works, just gives a 404. But of course the files are there - with the www-data:www-data owner - although symlinked.

Will now try to track down how to get the index.php file read by nginx - they may be being blocked by the Drupal config somehow, although as I said they have worked together pre-SSL.

**Comment by perusio** [comment]
Hey,

You don't need two vhosts. Use just one. Create a /piwik location in the
drupal vhost. Then just put **all** if the piwik configuration **inside**
that location.

Luke Spear <notifications@github.com> schrieb am Fr., 31. Juli 2015 10:40:

**Comment by luxpir** [comment]
Thanks. Much, much appreciated. Had forgotten we'd been in touch already (facepalm: https://groups.drupal.org/node/407348) pre-SSL. We're working again now, but I had to jostle a few things around, namely:

- matching the fcgicache zone name to Drupal's 'microcache',
- adding some fcgi_params similar to the Drupal ones but with the script filename line edited to include $document_root/piwik/index.php, all placed under the piwik/index.php location - more elegant solution would be to include those as a separate file, I suppose
- and of course adding a small location under the https server block for /piwik

We're working again. Thanks for your assistance. Leaving this up to hopefully reduce your support load in the future!
