### ISSUE TITLE
Use of caching piwik.php

### ISSUE THREAD

**Issue by MikeN123** [matomo-org/matomo-nginx#25]
Looking at the proposed config, I'm wondering what the use of the `piwik.php` cache is? The `piwik.php` file is used for tracking, thus:
- You do not want to cache any requests, since that would interfere with tracking
- Every request carries a unique query string, so nothing is cached with the current config

So, why is the caching config there?

**Comment by collinbarrett** [comment]
I'm interested on clarification on this, too.
