### ISSUE TITLE
Why override a lot of existing nginx files???

### ISSUE THREAD

**Issue by flip111** [matomo-org/matomo-nginx#27]
`git clone https://github.com/perusio/piwik-nginx.git /etc/nginx`

seems a bit crazy to advice to replace the current `nginx.conf` with the one from the repo just like that ...

yes ok you make a backup with `nginx.old` which should then be deleted later on??

Is there a configuration available that concentrate on just making piwik work and not mess around with all the fastcgi configuration and other not directly related piwik configs ??

**Comment by perusio** [comment]
Yes you shoulf backup your old nginx directory.
```shell
mv /etc/nginx /etc/nginx.old
```
I fail to see how FCGI is unrelated to piwik, you'll have to deal with it. It's how PHP communicates with nginx.

**Comment by flip111** [comment]
everything in the universe is related ... but piwik can run just as well on one worker_process than 4

https://github.com/perusio/piwik-nginx/blob/master/nginx.conf#L3

just to give you another example ...

Just my opinion the configuration should limit itself to the absolute neccesities, further can make recommendations but not enforce/override them.

How will i know which setting is absolutely neccesary for piwik to run?

**Comment by ttiurani** [comment]
This is my problem as well. From the configuration in this repository, it's really hard to find out what is actually needed to run Piwik under a subpath e.g. "example.com/piwik/index.php". Piwik isn't the only software that Nginx is proxying on my machine, so I'd just prefer to have one "/etc/nginx/sites-available/piwik.nginx.conf" file, alongside other service configuration files.

Did you @flip111 manage to create a simple Piwik configuration?

**Comment by flip111** [comment]
@ttiurani no sorry, my piwik installation is broken ever since this post (and before) and did not get around to fixing it ...

**Comment by anupamapanchal** [comment]
I have multiple website behind my nginx server and cloning the whole nginx folder and getting rid of the existing settings is lot more problematic. I agree with @flip111 that first provide us minimum configuration for running it on nginx and then this can be used for advance. Currently I am stuck with the installation and not able to find get arounds.

**Comment by xenithorb** [comment]
@anupamapanchal Here's a flat file I pieced together - https://gist.github.com/xenithorb/aa4252d1a43dc7c6660091df6189a948

**Comment by mattab** [comment]
Hi everyone, if anyone is interested please see my other issue:  New maintainer? #38

We'd love to have a simple Nginx conf maintained as official Piwik nginx conf. Looking for maintainers, Thanks @perusio for your work and hope to hear from you all!

**Comment by ttiurani** [comment]
In case anyone is interested, I have been successfully using the following `nginx.piwik.conf` in `sites-enabled`.

```
server {
  listen 8006;
  server_name localhost;

  location / {
    index index.php;

    location ~ ^/(.*\.(html|jpg|jpeg|gif|png|css|js|ico|xml|svg|ttf|woff))$ {
      alias /var/www/html/$1;
    }

    location ~ ^/(.*\.php) {
      set $request_url $1;

      fastcgi_param SCRIPT_FILENAME /var/www/html/$request_url;
      fastcgi_param REQUEST_URI /$request_url?$args;
      fastcgi_param HTTPS off;
      fastcgi_pass localhost:9000;
      include fastcgi_params;
      fastcgi_index  index.php;
    }
  }
}
```

**Comment by clessley** [comment]
@ttiurani is this working with nginx virtual hosts, ie, multiple sites on the same host with multiple nginx configs? I, too like @anupamapanchal cannot simply blow away other configs for piwik just to ditch google analytics.

**Comment by ttiurani** [comment]
@clessley yes, the above does work with multiple sites on same host. Don't quite remember the details of everything there unfortunately.

**Comment by clessley** [comment]
@ttiurani @mattab 

I dumped the most recent piwik install folder into one of my virtual sites' html directories. i then created a database/user and tried the installer; after installing a single required php dependency (which was flagged in the pre-install requirements list) install ran ok. i never used any type of nginx configuration at all as suggested.
