### ISSUE TITLE
nginx: [emerg] no port in upstream "phpcgi" in /etc/nginx/apps/piwik/piwik.conf:54

### ISSUE THREAD

**Issue by anupamapanchal** [matomo-org/matomo-nginx#28]
I went through the documentation but getting the following error
nginx: [emerg] no port in upstream "phpcgi" in /etc/nginx/apps/piwik/piwik.conf:54
Can you please help me out in this?

**Comment by ywiyogo** [comment]
I see also the same issue.

**Comment by Zachybear** [comment]
Same =(
