### ISSUE TITLE
unable to login on fresh installation

### ISSUE THREAD

**Issue by refuoe** [matomo-org/matomo-nginx#29]
I have a new installation of piwik on a nginx server, but im having a problem logging in with this error Error: Form security failed. Please reload the form and check that your cookies are enabled. If you use a proxy server, you must configure Piwik to accept the proxy header that forwards the Host header. Also, check that your Referer header is sent correctly. I tried on different browsers, cleared the cache,enabled cookies to no avail

I added these to my config.ini file:
[General]
assume_secure_protocol = 1
force_ssl=1
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
proxy_client_headers[] = HTTP_CLIENT_IP

Please help

**Comment by Findus23** [comment]
Hi, 

The nginx config has been rewritten from scratch, so if you or anyone else comes across the issue, please open a new issue.
