### ISSUE TITLE
Install instructions fail

### ISSUE THREAD

**Issue by johnfwhitmore** [matomo-org/matomo-nginx#33]
Perhaps the install instructions are outdated and perhaps I've misread those instructions and have missed a step. You can see the steps I took in trying to install piwik on an nginx server here:

http://www.johnwhitmore.org/blog/2016/10/02/installing-piwik-analytics/

I've asked questions on piwik forum where the proposed solution is install Apache web server.

**Comment by xenithorb** [comment]
https://gist.github.com/xenithorb/aa4252d1a43dc7c6660091df6189a948

I just pieced together this config from this repo and it works for me

look for `host.example.com` for user-specific areas that will need changing
