### ISSUE TITLE
Access to new php file is needed

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo-nginx#37]
We, the Piwik team, released a new feature yesterday called [Heatmap & Session Recording](https://www.heatmap-analytics.com/). In order for it to automatically work, it needs to make a request to a file "plugins/HeatmapSessionRecording/configs.php" when tracking. This file will for example decide if it is needed to record a visitors session or not.

It would be great to adjust piwik-nginx to make that file accessible.

**Comment by mattab** [comment]
fyi PR: https://github.com/perusio/piwik-nginx/pull/40
