### ISSUE TITLE
Don't have configuration errors by default

### ISSUE THREAD

**Issue by flip111** [matomo-org/matomo-nginx#46]
Some lines gives configuration errors, such as:

https://github.com/matomo-org/matomo-nginx/blob/14415ffd127722eb9b339e97bd1c621931ef6aa1/sites-available/matomo.conf#L22-L23

The reason is obvious .. the lines point to a non-existing file. The purpose of these lines is that they should be edited manually. I would like to ask that all lines that yield invalid configuration that need to be edited manually to be commented out or remove and place a description instead.

Right now i can not install the matomo nginx script and then run let's encrypt certbot because it will choke on these configuration errors. The two lines in the link in particularly don't need to be there because certbot will offer to add them (with nginx flag) if the conf file can be found.

I'm making an unattended install script and like as little manual intervention as possible.

**Comment by Findus23** [comment]
Hi,

I'm not sure, but wouldn't nginx not also throw an error if the ssl_certificate is missing?

**Comment by flip111** [comment]
I'm not sure about that either. I think the configuration would not work, but it won't be a critical error that prevents nginx from starting or checking for further problems. We need to test this.

**Comment by flip111** [comment]
What you say makes sense. Just that ... who would change config and NOT
restart/reload nginx? Is this a thing to change config while being online?
o_O

I can use sed for my purposes. But still I would recommend to minimize the
lines that give config errors.

Please feel free to close if my opinion is not shared.

**Comment by Findus23** [comment]
Hi,
Most of the time I only reload and not restart nginx, but regarding ssl certs it sometimes behaves a bit odd.

I think I'll close this unless someone also thinks the same.
