### ISSUE TITLE
Do not cache tag manager preview files

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo-nginx#48]
To make sure always the newest version of a preview container in tag manager is served, we should prevent the caching in the browser. For the apache version see https://github.com/matomo-org/matomo/pull/13977
`Header set Cache-Control "Cache-Control: private, no-cache, no-store"` for `^js/container_.*_preview\.js$`

Otherwise the user will need to use ctrl+r or something to reload a page that includes a preview file to make sure the cache is ignored and many users would not know that.

**Comment by Findus23** [comment]
Done:
```
curl -v https://matomo.example/js/container_PlwIwwkk_preview.js
.....
< HTTP/2 200 
< server: nginx
< date: Sat, 15 Jun 2019 13:56:30 GMT
< content-type: application/javascript
< content-length: 0
< last-modified: Sat, 15 Jun 2019 13:55:23 GMT
< etag: "5d04f8cb-0"
< cache-control: private, no-cache, no-store
< accept-ranges: bytes
```
