### ISSUE TITLE
Missing snippets/fastcgi-php.conf

### ISSUE THREAD

**Issue by ambroiseRabier** [matomo-org/matomo-nginx#51]
The comment state `# if your Nginx setup doesn't come with a default fastcgi-php config replace this with the one from this repository`. But there is not `fastcgi-php.conf` file in this repository.

Would be nice to provide one (even if it is super obvious what you should put into it, it is not for me).

**Comment by Findus23** [comment]
Hi,

This is the same as #49 which by chance I fixed yesterday in https://github.com/matomo-org/matomo-nginx/commit/0d634a2c66e2551d600ea5d9e022b2373a36f2c7.
