### ISSUE TITLE
Default configuration denies loading logo

### ISSUE THREAD

**Issue by jsabater** [matomo-org/matomo-nginx#76]
Just managed to install Matomo and found that, during the initial installation, the logo image at `plugins/Morpheus/images/logo.png` does not load.

The reason I've found is because it is being denied in the [sites-available/matomo.conf](https://github.com/matomo-org/matomo-nginx/blob/5b232af8ec1fd9d033f1c4ab9343f4073df64644/sites-available/matomo.conf#L80).

Thanks.

**Comment by michalkleiner** [comment]
Hi @jsabater,
the logo should be allowed by the rule above the one you linked — [this line](https://github.com/matomo-org/matomo-nginx/blob/5b232af8ec1fd9d033f1c4ab9343f4073df64644/sites-available/matomo.conf#L71).
The common problem related to the logo is accessing the site on HTTPS while the logo is loaded over HTTP.

**Comment by jsabater** [comment]
You're right. My bad, I had misplaced a couple of rules as I had not copy-pasted the referenced file into my server block. Thank you very much for your reply. :ok_hand:
